name = "deyxpress-tienda"
main = "worker.js"
compatibility_date = "2026-02-07"

[[d1_databases]]
binding = "DB"
database_name = "tareas-db"
database_id = "461bbbc7-d12f-4154-9a91-d827f329bbf7" # <-- Pon el ID que sacaste con 'npx wrangler d1 list'